apiVersion: apps/v1
kind: Deployment
metadata:
  name: Assembly-MG
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Assembly-MG
  template:
    metadata:
      labels:
        app: Assembly-MG
    spec:
      containers:
      - name: Assembly-MG
        image: Assembly-MG:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: Assembly-MG-service
spec: 
  ports:
  - port: 8001
    targetPort: 5001
    protocol: TCP
  selector:
    app: Assembly-MG
  type: LoadBalancer