apiVersion: apps/v1
kind: Deployment
metadata:
  name: assembly-mg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assembly-mg
  template:
    metadata:
      labels:
        app: assembly-mg
    spec:
      containers:
      - name: assembly-mg
        image: assembly-mg:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5100

---

apiVersion: v1
kind: Service
metadata:
  name: assembly-mg-service
spec: 
  ports:
  - port: 8100
    targetPort: 5100
    protocol: TCP
  selector:
    app: assembly-mg
  type: LoadBalancer