export const emptyValues = {
  "version": "1.5.1",
  "output":"",
  "resourcesDirectory":"",
  "threads":1,
  "experiments": "",
  "minimumReadLength":0,
  "minimumReadAverageQuality":0,
  "doAssembly":true,
  "assembler":"",
  "errorModel":"",
  "markerset":"",
  "doIterativeBinning":true,
  "diamondDatabase":"",
  "diamondMaxTargetSeqs":1,
  "downloadUniprot":true,
  "uniprotColumns":[],
  "uniprotDatabases":[],
  "recognizerDatabases":[],
  "normalizationMethod":"",
  "minimumDifferentialExpression":1.0,
  "keggcharterMaps":[],
  "keggcharterTaxaLevel":"",
  "keggcharterNumberOfTaxa":1,
  "proteomicsWorkflow":"",
  "useCrap":false,
  "proteomicsContaminantesDatabase":"",
  "referenceProteomesTaxaLevel":"",
  "protease":"",
  "proteaseFile":""
}
