apiVersion: apps/v1
kind: Deployment
metadata:
  name: annotation-mg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: annotation-mg
  template:
    metadata:
      labels:
        app: annotation-mg
    spec:
      containers:
      - name: annotation-mg
        image: annotation-mg:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: annotation-mg-service
spec: 
  ports:
  - port: 8000
    targetPort: 5000
    protocol: TCP
  selector:
    app: annotation-mg
  type: LoadBalancer